### ISSUE TITLE
[feature] introduce a lower boundary condition

### ISSUE THREAD

**Issue by g-voelker** [g-voelker/python-msgwam#2]
transform the initial value problem into a boundary value problem such that ray volumes are continuously fed at low altitudes

**Comment by g-voelker** [comment]
Pull request #6 contained lower boundary conditions for a continuously launched monochromatic wave, the Desubies spectrum, and a legacy for the case with an initial condition / wave packet. I guess I can close this issue, @dsconnelly ?

**Comment by dsconnelly** [comment]
Yes, I think so!
